In [1]:
import numpy as np

In [2]:
a = np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b = np.array(range(10, 15))
b

array([10, 11, 12, 13, 14])

In [7]:
np.concatenate((a, b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
l = list()
l.append(4)
l

[4]

In [9]:
l.extend([5, 6])
l

[4, 5, 6]

In [30]:
import glob

import tqdm
from pathlib import Path
p = Path('..')

ImportError: No module named 'tqdm'

In [29]:
list(p.glob('*'))

[PosixPath('../.DS_Store'),
 PosixPath('../.git'),
 PosixPath('../.gitignore'),
 PosixPath('../bokeh'),
 PosixPath('../compressive_sampling'),
 PosixPath('../graphs'),
 PosixPath('../README.md'),
 PosixPath('../requirements.txt'),
 PosixPath('../signal'),
 PosixPath('../sqllite'),
 PosixPath('../stats'),
 PosixPath('../tensorflow'),
 PosixPath('../venv')]